version: 2.1
jobs:
  build:
    docker:
      - image: "cimg/node:14.14.0"
    steps:
      - run: apk install python3
      - checkout
      - run: npm install
  test:
    docker:
      - image: "cimg/node:14.14.0"
    steps:
      - checkout
      - run: npm test
workflows:
  build_and_test:
    jobs:
      - build
      - test
