version: 2.1
jobs:
  build:
    docker:
      - image: "circleci/node:14.8.0"
    steps:
      - run: "apt-get update && apt-get install python3"
      - checkout
      - run: npm install
  test:
    docker:
      - image: "circleci/node:14.8.0"
    steps:
      - checkout
      - run: npm test
workflows:
  build_and_test:
    jobs:
      - build
      - test
