version: 2.1
jobs:
  build:
    docker:
      - image: "cimg/node:14.14.0"
    steps:
      - checkout
      - run: npm config set python /usr/bin/python3
      - run: npm install --also=dev
  test:
    docker:
      - image: "cimg/node:14.14.0"
    steps:
      - checkout
      - run: npm test
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
